services:
  worker-node-1:
    image: worker-node:latest
    build: ./worker
    ports:
      - "5001:5000"
    depends_on:
      - central-node
    networks:
      - app-network

  worker-node-2:
    image: worker-node:latest
    ports:
      - "5002:5000"
    build: ./worker
    depends_on:
      - central-node
    networks:
      - app-network

  worker-node-3:
    image: worker-node:latest
    build: ./worker
    ports:
      - "5003:5000"
    depends_on:
      - central-node
    networks:
      - app-network

  worker-node-4:
    image: worker-node:latest
    build: ./worker
    ports:
      - "5004:5000"
    depends_on:
      - central-node
    networks:
      - app-network

  central-node:
    image: central-node:latest
    build: ./central
    ports:
      - "5005:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
