apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-node
  template:
    metadata:
      labels:
        app: central-node
    spec:
      containers:
      - name: central-node
        image: central-node:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: central-node
spec:
  selector:
    app: central-node
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
