apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-node
spec:
  replicas: 4
  selector:
    matchLabels:
      app: worker-node
  template:
    metadata:
      labels:
        app: worker-node
    spec:
      containers:
      - name: worker-node
        image: worker-node:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: worker-node
spec:
  selector:
    app: worker-node
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
